### PR TITLE
Migrate to MongoDB Driver 2.0

### PR DESCRIPTION
**Pull request by rodrigograudo**
Migrating to MongoDB Driver 2.0 for new async capabilities of the c# driver.

### CODE REVIEW

**Comment by g0t4** [comment]
Hey, I’ll be taking a look at this later in the week, thanks so much for taking
this on

On Sun, Apr 5, 2015 at 11:34 AM, Rodrigo Graúdo < notifications@github.com [notifications@github.com] > wrote:
Migrating to MongoDB Driver 2.0 for new async capabilities of the c# driver.


--------------------------------------------------------------------------------

YOU CAN VIEW, COMMENT ON, OR MERGE THIS PULL REQUEST ONLINE AT:
https://github.com/g0t4/ aspnet-identity-mongo/pull/8
[https://github.com/g0t4/aspnet-identity-mongo/pull/8]

COMMIT SUMMARY
 * Migrate to MongoDB.Driver 2.0
 * Migrate to MongoDB.Driver 2.0

FILE CHANGES
 * D src/.nuget/packages.config
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-0] (4)
 * M src/AspNet.Identity.MongoDB. sln
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-1] (3)
 * M src/AspNet.Identity.MongoDB. sln.DotSettings
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-2] (3)
 * M src/AspNet.Identity.MongoDB/ AspNet.Identity.MongoDB.csproj
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-3] (16)
 * D src/AspNet.Identity.MongoDB/ IdentityContext.cs
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-4] (31)
 * M src/AspNet.Identity.MongoDB/ IndexChecks.cs
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-5] (50)
 * M src/AspNet.Identity.MongoDB/ RoleStore.cs
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-6] (110)
 * M src/AspNet.Identity.MongoDB/ UserStore.cs
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-7] (507)
 * M src/AspNet.Identity.MongoDB/ packages.config
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-8] (6)
 * M src/IntegrationTests/ EnsureWeCanExtendIdentityRoleT ests.cs
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-9] (101)
 * M src/IntegrationTests/ EnsureWeCanExtendIdentityUserT ests.cs
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-10] (101)
 * M src/IntegrationTests/ IdentityUserTests.cs
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-11] (38)
 * M src/IntegrationTests/ IndexChecksTests.cs
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-12] (60)
 * M src/IntegrationTests/ IntegrationTests.csproj
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-13] (25)
 * M src/IntegrationTests/ RoleStoreTests.cs
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-14] (13)
 * M src/IntegrationTests/ UserIntegrationTestsBase.cs
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-15] (62)
 * M src/IntegrationTests/ UserLoginStoreTests.cs
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-16] (195)
 * M src/IntegrationTests/ UserPasswordStoreTests.cs
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-17] (95)
 * M src/IntegrationTests/ UserRoleStoreTests.cs
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-18] (99)
 * M src/IntegrationTests/ UserSecurityStampStoreTests.cs
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-19] (53)
 * M src/IntegrationTests/ UserStoreTests.cs
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-20] (203)
 * M src/IntegrationTests/packages. config
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-21] (10)
 * M src/Tests/Tests.csproj
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-22] (25)
 * M src/Tests/packages.config
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8/files#diff-23] (10)

PATCH LINKS:
 * https://github.com/g0t4/ aspnet-identity-mongo/pull/8. patch
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8.patch]
 * https://github.com/g0t4/ aspnet-identity-mongo/pull/8. diff
   [https://github.com/g0t4/aspnet-identity-mongo/pull/8.diff]

—
Reply to this email directly or view it on GitHub [https://github.com/g0t4/aspnet-identity-mongo/pull/8] .[https://ci3.googleusercontent.com/proxy/seyNNUH8JBuBMq9WCXQ1R56nf_ulFiUoEPdOsUZLXIM86HHHgtiFGf9YaQb29hCZsfRXGhbFRKIfpskUKq9YK_XpKKp_RIYWIyx5_PAfJVaOFfA0VeLxsrjidkWBB_qCPieaXYnXhsTEUIx_Xm7t7cWH-gAbdg=s0-d-e1-ft#https://github.com/notifications/beacon/AAK_3ZxTlNT71aQa7YXgC9gfFYFyNLY0ks5n8U2EgaJpZM4D6hZU.gif]


[https://app.mixmax.com/api/track/v2/6ShmP3I21Enxuy7co/wes.mcclure%40gmail.com/gIt92YuIWdoRXan5SesBXZyB0MiRjZ1Y2MwU2Y5YTMhJTO0ADOxkzMxETMwADMwADMwY2YykzN5cDOmhjMlJmN1IWZ4UmM5EmM3gTZ0ITO5EmN3IWOiVTMkBzMyQTZkRmZiJDMwAzK5xGclJnI/gIvdmbv1WL5RXa05WZklWL0VmbwNXYvQDdwcmI?sc=false]
Sent with Mixmax [https://mixmax.com/s/yAvqbondLzZrHjgqb]

**Comment by rodrigograudo** [comment]
No problem. You helped me a lot creating this. =)
If you need any help just ask.

**Comment by leegreenwood** [comment]
I'm looking forward to getting my hands on this - Am running into the same problem, and need to update.

**Comment by nbarbettini** [comment]
Possibly dumb question, so forgive me if I'm missing something obvious: why are methods still being wrapped in `Task.Run(() => ...` if the underlying Mongo calls are now fully awaitable?

**Comment by rodrigograudo** [comment]
My mistake =X
I made this in a night really need some review.

**Comment by nbarbettini** [comment]
No worries. :) For the record, it does work! (compiled and tested these commits with a project I'm working on) I do think it would be cleaner to simply `return await` where possible.

**Comment by rodrigograudo** [comment]
Done @nbarbettini! Can you test it?

**Comment by nbarbettini** [comment]
Cool! I can test later today.

**Comment by rasmuschristensen** [comment]
So awesome to see this PR, would be happy to test it soon too

**Comment by nbarbettini** [comment]
@rodrigograudo My testing is by no means comprehensive, but it's working so far in the small sample app I've been playing with.

**Comment by g0t4** [comment]
Hey guys I'll test this out soon and yes I'll remove the Task.Run calls

**Comment by rodrigograudo** [comment]
Already removed @g0t4 but review is good

**Comment by g0t4** [comment]
I ported the library to the 2.0 driver, I want to leave the tests as-is as much as possible so I just updated the existing code and won't be merging this PR, though I've reviewed my changes and they look the same as yours for the most part. A few notes:

- I nuked IdentityContext, it wasn't serving much of a purpose anymore.
- IndexChecks, I made individual methods generic instead of the entire class.

**Comment by g0t4** [comment]
https://www.nuget.org/packages/AspNet.Identity.MongoDB/2.0.4-alpha

**Comment by rodrigograudo** [comment]
When you plan to release?

**Comment by g0t4** [comment]
Released on Friday

**Comment by rodrigograudo** [comment]
I mean a stable version.

**Comment by g0t4** [comment]
It's stable I just put it out as alpha in case people want to poke at it,
all tests are passing. I should just mark it as stable :)

**Comment by g0t4** [comment]
Stable is out 2.0.8

**Pull request closed without merging**
