### PR TITLE
Change BsonRepresentation for BsonId attribute in Id field.

### PR DESCRIPTION
**Pull request by diecamdia**
I've changed this attribute because when I try to connect to a mongo server I take one error.

### CODE REVIEW

**Comment by g0t4** [comment]
This would change how the _id field is stored from an ObjectId to a string, that's a breaking change versus how people are using this already and how I intended it. You would only get errors if you have documents with an _id field set to a string value. Did you manually import data to the collection? If so, change your import logic to use ObjectId instead.

**Comment by diecamdia** [comment]
Hi, i get the error when I am going to create the users and roles collections the first time against an empty database.  I didn`t import data manually.

**Comment by g0t4** [comment]
Could you post a stack trace

**Comment by diecamdia** [comment]
I do not understand anything, now it is working, I think is because I updated the MongoDB.Driver library. If I get the same error, I'll let you know. Thanks.

**Comment by g0t4** [comment]
That happens, good luck

**Pull request closed without merging**
